server:
  port: 8085

spring:
  application:
    name: CONFIGSERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/shivnarayan-1024/microservice-config1
          clone-on-start: true